### ISSUE TITLE
cannot load such file -- 

### ISSUE THREAD

**Issue by Tobi0484** [solectrus/tibber-collector#181]
Bekomme jetzt folgendes Protokoll beim collector:

```	
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendored_fileutils.rb:4:in `require_relative': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/fileutils/lib/fileutils (LoadError)
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendored_fileutils.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:3:in `require_relative'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:16:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendored_fileutils.rb:4:in `require_relative': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/fileutils/lib/fileutils (LoadError)
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendored_fileutils.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:3:in `require_relative'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:16:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
```

Was könnte hier falsch laufen?
Außer einem Neustart des RaspberryPI habe ich nichts weiter verändert...

**Comment by ledermann** [comment]
Seltsam, das kann ich bislang nicht reproduzieren. Könntest du bitte das vollständige Log posten, also vom Start des Containers bis zum Auftreten des Fehlers? Inklusive aller Versionssnummern am Anfang.

Außerdem wäre der Output folgender zwei Befehle nützlich:

```
lsb_release  -a
uname -a
```

**Comment by ledermann** [comment]
@Tobi0484 Bist du sicher, dass dein Raspi in Ordnung ist, insbesondere die SD-Karte keinen Defekt hat?

Ist möglicherweise das Docker-Image kaputt? Du könntest versuchen, das Image erneut herunterzuladen, und zwar so:

```
docker compose down
docker rmi ghcr.io/solectrus/tibber-collector
docker compose up -d
```

Ansonsten: Stammt der obige Log-Ausschnitt wirklich vom Tibber-Collector?

**Comment by Tobi0484** [comment]
Habe das Image neu gezogen, jetzt läuft wieder alles...

Vielen lieben Dank!

**Comment by ledermann** [comment]
Ok, das würde ich aber als Zeichen deuten, dass mit der SD-Karte etwas nicht stimmt. Die gehen gerne irgendwann auch kaputt. Am besten mal im Auge behalten.
