### ISSUE TITLE
Invalied field format - InfluxDB2:InfluxError

### ISSUE THREAD

**Issue by hj-hefer** [solectrus/tibber-collector#32]
Bekomme folgendes protokoll von dem Tibber-Collector:

```
docker-compose logs tibber-collector
WARN[0000] The "INFLUX_MEASUREMENT_PRICES" variable is not set. Defaulting to a blank string.
WARN[0000] The "INFLUX_MEASUREMENT_PRICES" variable is not set. Defaulting to a blank string.
solectrus-tibber-collector-1  | Tibber collector for SOLECTRUS, Version 0.2.3, built at 2024-01-28T06:46:31.925Z
solectrus-tibber-collector-1  | https://github.com/solectrus/tibber-collector
solectrus-tibber-collector-1  | Copyright (c) 2023-2024 Georg Ledermann, released under the MIT License
solectrus-tibber-collector-1  |
solectrus-tibber-collector-1  | Using Ruby 3.2.3 on platform x86_64-linux-musl
solectrus-tibber-collector-1  | Pulling from https://api.tibber.com/v1-beta/gql every 3600 seconds
solectrus-tibber-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket solectrus, measurement
solectrus-tibber-collector-1  |
solectrus-tibber-collector-1  | #1 - 2024-02-04 13:14:06 +0100
solectrus-tibber-collector-1  |   Fetching prices from Tibber ... OK
solectrus-tibber-collector-1  | bundler: failed to load command: app/main.rb (app/main.rb)
solectrus-tibber-collector-1  | /usr/local/bundle/gems/influxdb-client-3.0.0/lib/influxdb2/client/default_api.rb:106:in `_request': unable to parse 'amount=0.2334,level="NORMAL" 1707001200': invalid field format (InfluxDB2::InfluxError)
solectrus-tibber-collector-1  | unable to parse 'amount=0.2033,level="CHEAP" 1707004800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1952,level="CHEAP" 1707008400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1922,level="CHEAP" 1707012000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1914,level="CHEAP" 1707015600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1914,level="CHEAP" 1707019200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1914,level="CHEAP" 1707022800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1926,level="CHEAP" 1707026400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2019,level="CHEAP" 1707030000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2031,level="CHEAP" 1707033600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2043,level="CHEAP" 1707037200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2066,level="CHEAP" 1707040800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2078,level="CHEAP" 1707044400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1969,level="CHEAP" 1707048000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2029,level="CHEAP" 1707051600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2101,level="CHEAP" 1707055200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2133,level="CHEAP" 1707058800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2377,level="NORMAL" 1707062400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2461,level="NORMAL" 1707066000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2344,level="NORMAL" 1707069600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2259,level="NORMAL" 1707073200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2205,level="NORMAL" 1707076800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2204,level="NORMAL" 1707080400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.192,level="CHEAP" 1707084000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1914,level="CHEAP" 1707087600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1913,level="CHEAP" 1707091200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1913,level="CHEAP" 1707094800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1912,level="CHEAP" 1707098400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1913,level="CHEAP" 1707102000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1919,level="CHEAP" 1707105600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2377,level="NORMAL" 1707109200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2615,level="NORMAL" 1707112800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2655,level="EXPENSIVE" 1707116400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.259,level="NORMAL" 1707120000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2544,level="NORMAL" 1707123600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2391,level="NORMAL" 1707127200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1998,level="CHEAP" 1707130800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1927,level="CHEAP" 1707134400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.1973,level="CHEAP" 1707138000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2546,level="NORMAL" 1707141600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2636,level="EXPENSIVE" 1707145200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2728,level="EXPENSIVE" 1707148800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2732,level="EXPENSIVE" 1707152400': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.265,level="EXPENSIVE" 1707156000': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2633,level="EXPENSIVE" 1707159600': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2623,level="EXPENSIVE" 1707163200': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2584,level="NORMAL" 1707166800': invalid field format
solectrus-tibber-collector-1  | unable to parse 'amount=0.2478,level="NORMAL" 1707170400': invalid field format
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/influxdb-client-3.0.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/influxdb-client-3.0.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/influxdb-client-3.0.0/lib/influxdb2/client/write_api.rb:186:in `write'
solectrus-tibber-collector-1  |         from /tibber-collector/app/flux_writer.rb:33:in `push'
solectrus-tibber-collector-1  |         from /tibber-collector/app/flux_writer.rb:12:in `push'
solectrus-tibber-collector-1  |         from /tibber-collector/app/loop.rb:48:in `push_to_influx'
solectrus-tibber-collector-1  |         from /tibber-collector/app/loop.rb:26:in `block in start'
solectrus-tibber-collector-1  |         from /tibber-collector/app/loop.rb:21:in `loop'
solectrus-tibber-collector-1  |         from /tibber-collector/app/loop.rb:21:in `start'
solectrus-tibber-collector-1  |         from /tibber-collector/app/loop.rb:15:in `start'
solectrus-tibber-collector-1  |         from app/main.rb:26:in `<top (required)>'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
solectrus-tibber-collector-1  |         from /usr/local/bundle/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
solectrus-tibber-collector-1  |         from /usr/local/bundle/bin/bundle:25:in `load'
solectrus-tibber-collector-1  |         from /usr/local/bundle/bin/bundle:25:in `<main>'
```

Ich gehe mal davon aus das irgend ein Fehler noch vorhanden ist mit dem invalid field format.

mfg
H.-J. Hefer

**Comment by ledermann** [comment]
Die wichtigsten Zeilen sind diese hier:

```
WARN[0000] The "INFLUX_MEASUREMENT_PRICES" variable is not set. Defaulting to a blank string.
WARN[0000] The "INFLUX_MEASUREMENT_PRICES" variable is not set. Defaulting to a blank string.
````

In deiner deiner `.env` sollte etwas das hier stehen:

```
INFLUX_MEASUREMENT_PRICES=my-prices
INFLUX_MEASUREMENT_FORECAST=my-forecast
```

In der `docker-compose.yml` außerdem:

```
services:
  ...
  tibber-collector:
    ...
    environment:
      ...
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_PRICES}
```


Das bedeutet: In der `.env` werden die Namen der verschiedenen Messreihen ("measurements") für InfluxDB in Variablen festgelegt. Einzelne Container picken sich dann (per docker-compose.yml) die benötigten Variablen heraus, benennen sie dabei aber um. Die Variable "INFLUX_MEASUREMENT_PRICES" heißt im Tibber-Collector dann einfach nur noch "INFLUX_MEASUREMENT".

Vermutlich ist das bei Dir irgendwie durcheinander gekommen. Falls dir die Erklärung nicht hilft, poste bitte mal `.env` und `docker-compose.yml`.

**Comment by hj-hefer** [comment]
Hallo und vielen Dank für die sehr schnelle Rückmeldung.
Es lag wirklich an der .env Datei. Dort habe ich die beiden Einträge 
INFLUX_MEASUREMENT_PRICES=my-prices
INFLUX_MEASUREMENT_FORECAST=my-forecast
nicht eingebaut. 
Nun kommt keine Meldung mehr.

Sollten noch probleme mit dem laden des Speichers kommen melde ich mich noch einmal.

Schönen Sonntag noch
H.-J. Hefer

**Comment by ledermann** [comment]
Bestens, dann schließe ich dieses Issue. Bei weiteren Problemen bitte neues Issue aufmachen.
